In [209]:
import numpy as np

In [210]:
points = np.array([ [0.1,0.1,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0], [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0], [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0], [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0], [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0] ])

In [211]:
points20 = points * 20.0
points_int = points20.astype(int)

In [212]:
x = np.zeros((20, 20))

In [213]:
i = 0
j = 1
for i, j in zip(range(10), range(10)):
    c_x = points_int[0,i]
    c_j = points_int[0,j]
    i=i+2
    j=j+2
    
    x[c_x-1, c_j-1] = 255

    

In [214]:
x

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0., 255.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0., 255.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0

In [215]:
out = np.reshape(x, 400)

In [216]:
out

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0., 255.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0., 255.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0., 255.,   0.,   0.,   

In [217]:
np.shape(out)


(400,)

In [218]:
result = np.where(x == 255)

In [219]:
result

(array([ 1,  5,  7,  9, 11, 13, 15, 17, 19], dtype=int64),
 array([ 1,  5,  7,  9, 11, 13, 15, 17, 19], dtype=int64))