In [102]:
import numpy as np
import pandas as pd
from scipy.spatial.distance import squareform, pdist



In [13]:
a = np.array([ [0,0], [1,2], [3,4], [5,6], [7,8] ])
a

array([[0, 0],
       [1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [222]:
np.shape(a)

(5, 2)

In [33]:
out = squareform(pdist(a))

In [34]:
out

array([[ 0.        ,  2.23606798,  5.        ,  7.81024968, 10.63014581],
       [ 2.23606798,  0.        ,  2.82842712,  5.65685425,  8.48528137],
       [ 5.        ,  2.82842712,  0.        ,  2.82842712,  5.65685425],
       [ 7.81024968,  5.65685425,  2.82842712,  0.        ,  2.82842712],
       [10.63014581,  8.48528137,  5.65685425,  2.82842712,  0.        ]])

In [29]:
print(np.shape(out))

(25,)


In [22]:
x = np.reshape(out, 25)

In [23]:
x

array([ 0.        ,  2.23606798,  5.        ,  7.81024968, 10.63014581,
        2.23606798,  0.        ,  2.82842712,  5.65685425,  8.48528137,
        5.        ,  2.82842712,  0.        ,  2.82842712,  5.65685425,
        7.81024968,  5.65685425,  2.82842712,  0.        ,  2.82842712,
       10.63014581,  8.48528137,  5.65685425,  2.82842712,  0.        ])

In [24]:
np.shape(x)

(25,)

In [41]:
# sum of each row in out matrix


rows = len(out);  
cols = len(out[0]);  

In [39]:
rows

5

In [40]:
cols

5

In [120]:
out_summed = np.array([])


for i in range(0, rows):  
    sumRow = 0;  
    for j in range(0, cols):  
        sumRow = sumRow + out[i][j];
    out_summed = np.append(out_summed, [sumRow], axis=0)
    

In [121]:
out_summed

array([25.67646347, 19.20663073, 16.3137085 , 19.12395817, 27.60070856])

In [124]:
matrix = np.matrix(out_summed)

In [125]:
matrix

matrix([[25.67646347, 19.20663073, 16.3137085 , 19.12395817, 27.60070856]])

In [155]:
# convert array into dataframe
DF = pd.DataFrame(matrix, columns=['A', 
                      'B', 'C', 'D', 'E' ], index = ['1'])
DF2 = pd.DataFrame(matrix, columns=['A', 
                      'B', 'C', 'D', 'E' ], index = ['2'])

# DF.append(DF2)
DF = pd.concat([DF, DF2])
DF.to_csv("dataset.csv")

In [ ]:
# read from raw dataset

In [157]:
import pandas as pd
 
# creating a data frame
raw_df = pd.read_csv("raw.csv")
print(raw_df.head())

   No                          Point A                          Point B  \
0   1  0.2807019358965,0.4244344252102  0.4211343666572,0.4556416320459   
1   3  0.5256835405573,0.2245299934992  0.1309621903588,0.5303057532548   
2   4             0.3218181818182,0.41             0.3872727272727,0.81   
3   6   0.587052300456,0.2490774974587  0.6729685643142,0.0588343417727   
4   8           0.3148,0.3020909090909           0.3144,0.1093090909091   

                           Point C                          Point D  \
0  0.5366010319493,0.4275551458938  0.8549145416735,0.4181929838431   
1  0.2802085009625,0.1866406978221   0.2249766170537,0.616222017113   
2  0.8963636363636,0.3554545454545  0.4236363636364,0.3918181818182   
3  0.8754854719799,0.2541463337106  0.6545579363446,0.5978113891433   
4  0.8963636363636,0.3554545454545           0.3792,0.2545090909091   

                           Point E Error Classification  
0  0.6801541833936,0.4244344252102                    A  
1  0.2

In [158]:
columns = ['Point A', 'Point B', 'Point C', 'Point D', 'Point E']
raw_df_selected = raw_df[columns]

In [163]:
raw_df_selected_array = raw_df_selected[['Point A', "Point B", "Point C", "Point D", "Point E"]].to_numpy()
np.shape(raw_df_selected_array)

(45, 5)

In [166]:
raw_df_selected_array[0,0]

'0.2807019358965,0.4244344252102'

In [167]:
point = repr(raw_df_selected_array[0,0])

In [168]:
point

"'0.2807019358965,0.4244344252102'"

In [181]:
my_string = raw_df_selected_array[0,0]
my_list = my_string.split(",")
print(float(my_list[0]))

0.2807019358965


In [258]:
c = np.array([])

In [269]:
c = np.append(c, [0,0] )

In [261]:
c

array([0., 0.])

In [270]:
np.shape(c)

(10,)

In [271]:
d = np.reshape(c, (5,2))

In [272]:
d

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])