In [185]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [186]:
from sklearn.datasets import make_blobs
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [187]:
df = pd.read_csv("../dataset/dataset_with_error_cnn.csv")
df

Unnamed: 0   Point A   Point B   Point C   Point D   Point E  \
0             0  1.373475  0.958978  0.836790  1.502963  0.978804   
1             1  1.940213  1.371291  1.743612  1.315589  2.017418   
2             2  1.690368  2.025028  2.025214  1.518278  1.934396   
3             3  1.542669  1.888478  1.641450  1.641526  2.550871   
4             4  1.429971  1.580948  1.820888  1.274735  1.757213   
..          ...       ...       ...       ...       ...       ...   
306         306  0.234889  0.341797  0.312052  0.323540  0.359836   
307         307  0.235683  0.339810  0.340483  0.328003  0.329723   
308         308  0.231840  0.313921  0.329652  0.349243  0.341359   
309         309  0.237851  0.306959  0.316966  0.357427  0.358833   
310         310  0.234731  0.343230  0.315228  0.321040  0.357567   

     Error Classification  
0                       0  
1                       1  
2                       0  
3                       1  
4                       0  
..                    ...  
306                     4  
307                     4  
308                     4  
309                     4  
310                     4  

[311 rows x 7 columns]

In [188]:
df = df.drop('Unnamed: 0', axis=1)
df

Point A   Point B   Point C   Point D   Point E  Error Classification
0    1.373475  0.958978  0.836790  1.502963  0.978804                     0
1    1.940213  1.371291  1.743612  1.315589  2.017418                     1
2    1.690368  2.025028  2.025214  1.518278  1.934396                     0
3    1.542669  1.888478  1.641450  1.641526  2.550871                     1
4    1.429971  1.580948  1.820888  1.274735  1.757213                     0
..        ...       ...       ...       ...       ...                   ...
306  0.234889  0.341797  0.312052  0.323540  0.359836                     4
307  0.235683  0.339810  0.340483  0.328003  0.329723                     4
308  0.231840  0.313921  0.329652  0.349243  0.341359                     4
309  0.237851  0.306959  0.316966  0.357427  0.358833                     4
310  0.234731  0.343230  0.315228  0.321040  0.357567                     4

[311 rows x 6 columns]

In [189]:
from sklearn.model_selection import train_test_split

X = df.drop('Error Classification',axis=1)

y = df['Error Classification']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101)

In [190]:
tf.random.set_seed(1234)  # applied to achieve consistent results
model = Sequential(
    [
        Dense(5, activation = 'relu',   name = "L1"),
        Dense(5, activation = 'linear', name = "L2")

    ]
)

In [191]:
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(0.01),
    metrics = ['accuracy']
)

model.fit(
    X_train,y_train,
    epochs=200
)

Epoch 1/200
7/7 [==============================] - 0s 1ms/step - loss: 1.4142 - accuracy: 0.2627
Epoch 2/200
7/7 [==============================] - 0s 1ms/step - loss: 1.3471 - accuracy: 0.2673
Epoch 3/200
7/7 [==============================] - 0s 1ms/step - loss: 1.3033 - accuracy: 0.2765
Epoch 4/200
7/7 [==============================] - 0s 1ms/step - loss: 1.2629 - accuracy: 0.5253
Epoch 5/200
7/7 [==============================] - 0s 1ms/step - loss: 1.2179 - accuracy: 0.5346
Epoch 6/200
7/7 [==============================] - 0s 1ms/step - loss: 1.1585 - accuracy: 0.5392
Epoch 7/200
7/7 [==============================] - 0s 1ms/step - loss: 1.1062 - accuracy: 0.5668
Epoch 8/200
7/7 [==============================] - 0s 1ms/step - loss: 1.0611 - accuracy: 0.5853
Epoch 9/200
7/7 [==============================] - 0s 1ms/step - loss: 1.0192 - accuracy: 0.6820
Epoch 10/200
7/7 [==============================] - 0s 984us/step - loss: 0.9774 - accuracy: 0.7788
Epoch 11/200
7/7 [=========

In [192]:
y_pred = model.predict(X_test)

3/3 [==============================] - 0s 1ms/step


In [193]:
np.shape(X_test)

(94, 5)

In [194]:
y_pred

array([[-1.17213023e+00,  8.78036022e-01, -4.33223772e+00,
        -3.04460073e+00,  4.55978537e+00],
       [ 2.59292412e+00,  1.89523053e+00,  2.63979387e+00,
        -4.30193424e+00, -1.91907139e+01],
       [-1.17213023e+00,  8.78036022e-01, -4.33223772e+00,
        -3.04460073e+00,  4.55978537e+00],
       [ 5.36647415e+00,  3.03276324e+00,  6.03959322e+00,
        -5.90760994e+00, -2.87835674e+01],
       [-1.36371374e+01, -7.94364214e+00, -3.02256012e+00,
         1.06638451e+01, -2.78412647e+01],
       [ 3.99398565e+00,  1.77400327e+00,  7.46926355e+00,
        -3.89514613e+00, -3.82025719e+01],
       [-6.03048658e+00, -3.47841120e+00,  2.84290314e-01,
         3.90529847e+00, -2.67595673e+01],
       [-7.60667133e+00, -4.65369654e+00,  7.17319965e-01,
         5.74336910e+00, -3.20739403e+01],
       [-1.17213023e+00,  8.78036022e-01, -4.33223772e+00,
        -3.04460073e+00,  4.55978537e+00],
       [-7.32883096e-01, -1.11095238e+00,  5.90721178e+00,
         4.97581959e-01

In [195]:
# Importing the libraries that we will be using for building the neural network
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [196]:
# importing the classes for building the neural network layers
from tensorflow.keras.layers import Dense,Input,Concatenate

In [197]:
initialiezer=tf.keras.initializers.RandomUniform(minval=0.0005, maxval=1, seed=100)

input1= Input(shape=1)
input2= Input(shape=1)
input3= Input(shape=1)
input4= Input(shape=1)
input5= Input(shape=1)

l1=Dense(units=5,use_bias=True,activation='relu',kernel_initializer=initialiezer)(input1)
l1=Dense(units=5,use_bias=True,activation='relu',kernel_initializer=initialiezer)(l1)

l2=Dense(units=5,use_bias=True,activation='relu',kernel_initializer=initialiezer)(input2)
l2=Dense(units=5,use_bias=True,activation='relu',kernel_initializer=initialiezer)(l2)

concatted = Concatenate()([l1, l2])
out=Dense(units=1,use_bias=True,activation='sigmoid',kernel_initializer=initialiezer)(concatted)


In [198]:
from tensorflow.keras.models import Model

In [199]:
model=Model([input1,input2,input3,input4,input5],[out])

In [200]:
from keras.utils.vis_utils import plot_model
plot_model(model, to_file='model_plot.png', show_shapes=True, show_layer_names=True)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


In [201]:
import pandas
inputDataFrame=pandas.read_csv("../dataset/dataset_with_error_cnn.csv")
inputDataFrame

Unnamed: 0   Point A   Point B   Point C   Point D   Point E  \
0             0  1.373475  0.958978  0.836790  1.502963  0.978804   
1             1  1.940213  1.371291  1.743612  1.315589  2.017418   
2             2  1.690368  2.025028  2.025214  1.518278  1.934396   
3             3  1.542669  1.888478  1.641450  1.641526  2.550871   
4             4  1.429971  1.580948  1.820888  1.274735  1.757213   
..          ...       ...       ...       ...       ...       ...   
306         306  0.234889  0.341797  0.312052  0.323540  0.359836   
307         307  0.235683  0.339810  0.340483  0.328003  0.329723   
308         308  0.231840  0.313921  0.329652  0.349243  0.341359   
309         309  0.237851  0.306959  0.316966  0.357427  0.358833   
310         310  0.234731  0.343230  0.315228  0.321040  0.357567   

     Error Classification  
0                       0  
1                       1  
2                       0  
3                       1  
4                       0  
..                    ...  
306                     4  
307                     4  
308                     4  
309                     4  
310                     4  

[311 rows x 7 columns]

In [202]:
inputDataFrame = inputDataFrame.drop('Unnamed: 0', axis=1)
inputDataFrame

Point A   Point B   Point C   Point D   Point E  Error Classification
0    1.373475  0.958978  0.836790  1.502963  0.978804                     0
1    1.940213  1.371291  1.743612  1.315589  2.017418                     1
2    1.690368  2.025028  2.025214  1.518278  1.934396                     0
3    1.542669  1.888478  1.641450  1.641526  2.550871                     1
4    1.429971  1.580948  1.820888  1.274735  1.757213                     0
..        ...       ...       ...       ...       ...                   ...
306  0.234889  0.341797  0.312052  0.323540  0.359836                     4
307  0.235683  0.339810  0.340483  0.328003  0.329723                     4
308  0.231840  0.313921  0.329652  0.349243  0.341359                     4
309  0.237851  0.306959  0.316966  0.357427  0.358833                     4
310  0.234731  0.343230  0.315228  0.321040  0.357567                     4

[311 rows x 6 columns]

In [203]:
# Getting the data out as numpy arrays
x1s=inputDataFrame['Point A'].to_numpy()
x2s=inputDataFrame['Point B'].to_numpy()
x3s=inputDataFrame['Point C'].to_numpy()
x4s=inputDataFrame['Point D'].to_numpy()
x5s=inputDataFrame['Point E'].to_numpy()
ys=inputDataFrame['Error Classification'].to_numpy()

In [204]:
x1s=x1s.reshape(x1s.shape[0],1)
x2s=x2s.reshape(x2s.shape[0],1)
x3s=x3s.reshape(x3s.shape[0],1)
x4s=x4s.reshape(x4s.shape[0],1)
x5s=x5s.reshape(x5s.shape[0],1)
ys=ys.reshape(ys.shape[0],1)

In [205]:
import sklearn
from sklearn.model_selection import train_test_split
x1Train, x1Test, x2Train, x2Test, x3Train, x3Test, x4Train, x4Test, x5Train, x5Test, yTrain, yTest = train_test_split(x1s,x2s,x3s,x4s,x5s,ys, test_size=0.20, random_state=42)

In [206]:
print(f'the shape of x1Train = {x1Train.shape}')
print(f'the shape of x1Test = {x1Test.shape}')

print(f'the shape of x2Train = {x5Train.shape}')
print(f'the shape of x2Test = {x5Test.shape}')

print(f'the shape of x3Train = {x5Train.shape}')
print(f'the shape of x3Test = {x5Test.shape}')

print(f'the shape of x4Train = {x5Train.shape}')
print(f'the shape of x4Test = {x5Test.shape}')

print(f'the shape of x5Train = {x5Train.shape}')
print(f'the shape of x5Test = {x5Test.shape}')


print(f'the shape of yTrain = {yTrain.shape}')
print(f'the shape of yTest = {yTest.shape}')

the shape of x1Train = (248, 1)
the shape of x1Test = (63, 1)
the shape of x2Train = (248, 1)
the shape of x2Test = (63, 1)
the shape of x3Train = (248, 1)
the shape of x3Test = (63, 1)
the shape of x4Train = (248, 1)
the shape of x4Test = (63, 1)
the shape of x5Train = (248, 1)
the shape of x5Test = (63, 1)
the shape of yTrain = (248, 1)
the shape of yTest = (63, 1)


In [207]:
model.compile(loss='mse',metrics=['mse'],optimizer=tf.optimizers.Adam(learning_rate=0.01))

In [208]:
# model.compile(
#     loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
#     optimizer=tf.keras.optimizers.Adam(0.01),
#     metrics = ['accuracy']
# )


In [209]:
# train the model. just run a few epochs for this test run. you can adjust later.
history=model.fit(x=[x1Train,x2Train,x3Train,x4Train,x5Train],y=[yTrain],validation_data=([x1Test,x2Test,x3Test,x4Test,x5Test],[yTest]),batch_size=256, epochs=300)

Epoch 1/300
1/1 [==============================] - 1s 880ms/step - loss: 4.6377 - mse: 4.6377 - val_loss: 4.1628 - val_mse: 4.1628
Epoch 2/300
1/1 [==============================] - 0s 28ms/step - loss: 4.5607 - mse: 4.5607 - val_loss: 4.1011 - val_mse: 4.1011
Epoch 3/300
1/1 [==============================] - 0s 31ms/step - loss: 4.4884 - mse: 4.4884 - val_loss: 4.0452 - val_mse: 4.0452
Epoch 4/300
1/1 [==============================] - 0s 29ms/step - loss: 4.4223 - mse: 4.4223 - val_loss: 3.9959 - val_mse: 3.9959
Epoch 5/300
1/1 [==============================] - 0s 31ms/step - loss: 4.3636 - mse: 4.3636 - val_loss: 3.9536 - val_mse: 3.9536
Epoch 6/300
1/1 [==============================] - 0s 29ms/step - loss: 4.3128 - mse: 4.3128 - val_loss: 3.9184 - val_mse: 3.9184
Epoch 7/300
1/1 [==============================] - 0s 30ms/step - loss: 4.2701 - mse: 4.2701 - val_loss: 3.8897 - val_mse: 3.8897
Epoch 8/300
1/1 [==============================] - 0s 29ms/step - loss: 4.2351 - mse: 4.2

In [210]:
input=[x1Test[60],x2Test[60],x3Test[60],x4Test[60],x4Test[60]]
output=model.predict(input)

1/1 [==============================] - 0s 67ms/step


In [211]:
input

[array([2.78251585]),
 array([2.98232124]),
 array([2.37517084]),
 array([2.83734284]),
 array([2.83734284])]

In [212]:
yTest[60]

array([3], dtype=int64)

In [213]:
output

array([[1.]], dtype=float32)